### ISSUE TITLE
1.3.0 not working with up-to-date KeePass

### ISSUE THREAD

**Issue by computergeek125** [cyrbil/python_keepass_http#4] opened 2019-10-25 16:49 UTC
KeePassHTTP python version 1.3.0 returns an exception on both Windows native python and Cygwin when collecting a credential.  This works if I revert the keepasshttp module to 1.2.3.

* KeePass version: 2.43
* KeePassHTTP version: 1.8.4.2
* Python module: 1.3.0
* Python version: 3.6.9 (cygwin)
* Python version: 3.7.4 (native)
* OS: Windows 7 x64

Example code:
```python
import keepasshttp

kp = keepasshttp.KeePassHTTP(url="localhost:19455")
print(kp.get("www.example.com"))
```

Exception is the same on both platforms.  KeePass will generate (and regenerate) the correct encryption keys and prompt to add them in the UI.  I know for some libraries it's possible to mess with the trace logging to get more info about the error, but I'm not sure how to do that for this.  From a debugging stance, I'm not sure where to look in KPH to find out what that bad response was.
```python
Traceback (most recent call last):
  File "keepass_test.py", line 4, in <module>
    print(kp.get("www.example.com"))
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 130, in get
    entries = self.search(key)
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 113, in search
    data = self._request("get-logins", Url=key, SortSelection=sort_keys)
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 189, in _request
    self._load()
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 168, in _load
    self._authenticate()
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 185, in _authenticate
    self._request("test-associate")
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 207, in _request
    raise KeePassHTTPException("KeePassHTTP returned an error")  # pragma: no cover
keepasshttp.keepass_http.KeePassHTTPException: KeePassHTTP returned an error
```

### Dependency notes:
Here's what pip shows it had on hand as dependencies:
```shell
$ pip3 install keepasshttp --upgrade
Collecting keepasshttp
  Using cached https://files.pythonhosted.org/packages/6a/00/552d4f6d14dd814c8902f4ad694aef1ec04cafccd9cec3d0bb8e4925c042/keepasshttp-1.3.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: six>=1.12.0 in /usr/lib/python3.6/site-packages (from keepasshttp) (1.12.0)
Requirement already satisfied, skipping upgrade: pycryptodome>=3.8.2 in /usr/lib/python3.6/site-packages (from keepasshttp) (3.9.0)
Requirement already satisfied, skipping upgrade: requests>=2.19.1 in /usr/lib/python3.6/site-packages (from keepasshttp) (2.21.0)
Requirement already satisfied, skipping upgrade: ordereddict>=1.1 in /usr/lib/python3.6/site-packages (from keepasshttp) (1.1)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests>=2.19.1->keepasshttp) (1.24.1)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3.6/site-packages (from requests>=2.19.1->keepasshttp) (2.8)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests>=2.19.1->keepasshttp) (3.0.4)
Installing collected packages: keepasshttp
  Found existing installation: keepasshttp 1.2.3
    Uninstalling keepasshttp-1.2.3:
      Successfully uninstalled keepasshttp-1.2.3
Successfully installed keepasshttp-1.3.0
```

**Comment by cyrbil** [comment] 2019-10-25 19:09
Thank you for the thorough investigation. `KeePassHTTP` has some stacktraces available. But could also add a bit more information.

I will try to reproduce it on my side and come up with a fix.

**Comment by cyrbil** [comment] 2019-10-29 12:16
Ok, so I tried to hit that bug with the same version of `KeePass` and `KeePassHTTP` that you had, but everything was fine and all tests passes.

KeePass version: 2.43
KeePassHTTP version: 1.8.4.2

I will publish a new version of this package that add more details in the logs and traces. When published, could you retry and give me the trace again ?

**Comment by cyrbil** [comment] 2019-11-09 13:04
`KeePassHTTP` v1.4.0 has been released, please see if it solve issue or show more details ?

**Comment by richboss** [comment] 2019-11-12 22:10
I've got the same problem as computergeek125, and for me release 1.4.0 does not fix it. But I might be able to give a helpful hint. For me the root cause of the problem appears to be a bug in the refactoring of the _encrypt() function between releases 1.2.3 and 1.3.0. That function now returns - after some `if...elif...` clauses - with a `str(data).lower()` statement. Unfortunately this messes with the 'Id' value of the request_data if that value contains uppercase letters. If you add debug print lines before and after the encryption of the request data, you can see that before encryption the Id is, for example, 'SECRETSAUCE', and after encryption it is 'secretsauce'. If I delete the `.lower()' conversion at the end of the _encrypt() function, the exception goes away and everything seems to work. But I don't think that would be a proper fix, since presumedly the lower case conversion is principally there for a reason and if it is taken away completely there could arise problems somewhere else.

**Comment by computergeek125** [comment] 2019-11-12 22:18
Sorry, didn't see this until today.  If the API is not expected to change between the versions, I get this when upgrading working software from 1.2.3 to 1.4.0

```python
Traceback (most recent call last):
  File "*******.py", line 316, in <module>
    init()
  File "*******.py", line 127, in init
    ******* = login.keepass(args.url, session=session)
  File "/cygdrive/c/src/*******/*******.py", line 23, in keepass
    credential = kp.get(url)
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 174, in get
    entries = self.search(key)
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 157, in search
    data = self._request("get-logins", Url=key, SortSelection=sort_keys)
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 233, in _request
    self._load()
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 212, in _load
    self._authenticate()
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 229, in _authenticate
    self._request("test-associate")
  File "/usr/lib/python3.6/site-packages/keepasshttp/keepass_http.py", line 251, in _request
    raise KeePassHTTPBadResponse(response)  # pragma: no cover
KeePassHTTP server return an error
Status: 200 - Body: b'{"RequestType":"test-associate","Success":false,"Count":0,"Version":"1.8.4.2","Hash":"*******"}'
keepasshttp.keepass_http.KeePassHTTPBadResponse: KeePassHTTP server return an error
Status: 200 - Body: b'{"RequestType":"test-associate","Success":false,"Count":0,"Version":"1.8.4.2","Hash":"*******"}'
```

**Comment by cyrbil** [comment] 2019-11-12 23:49
Thank you for the feedbacks guys, really helpful!
The  `lower()` statement might be the root cause and since the testcases don't use case sensitive `Id` that would explain the why the `test-associate` query fails.

I will remove it and test again when I have some time to check it out.

**Comment by madtools** [comment] 2020-01-15 14:51
I have the same issue.  Since the upgrade from 1.2.3 to 1.4.0, if create a new association with an ID with an uppercase character, the next command will return an error.  If I use an all lowercase ID, the commands will work.

So I agree with your conclusion, you need to remove the .lower() of the data in the _encrypt method.

Thanks in advance for the fix.

**Comment by just-grizzle** [comment] 2020-10-07 17:37
Removing that command in my local copy manually solved the problem, too.
@cyrbil Any reason not to apply this?

**Comment by cyrbil** [comment] 2020-10-07 18:20
Well, I kinda let this issue sits ...
Reason was that during my tests on various environment + kph version, I was not able to find a stable fix.

@just-grizzle which command ? `lower()` ? 

If someone has used a version without the lower part for some time, could you raise your hand ?
Will try to release a version this week with the fix, because it's blocking anyway.

**Comment by cyrbil** [comment] 2020-10-20 17:46
Fixed in latest version.

**Closed** 2020-10-20 17:46 UTC
Labels: Priority: Low, Status: On Hold, Type: Bug, good first issue, help wanted

**Comment by just-grizzle** [comment] 2020-10-28 16:17
Sorry, did not see you answered. I removed the `lower()`, that's what worked for me.

**Comment by computergeek125** [comment] 2021-08-10 20:22
My project got stuck on the back burner for a bit, but to loop back on this, 1.4.1 installed from `pip` appears to be working
